databaseType = "PostgreSql"
id = "ab831a3d-1363-4851-8c10-304814d9b85e"
name = "flyway-longthdb001"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
enableMigrations = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.longthdb001-local]
url = "jdbc:postgresql://localhost:5432/longthdb001"
schemas = [ "longth001" ]
displayName = "longthdb001"
